[project]
name = "Galinhada do Chefão"
version = "0.1.0"
description = "Gerencie esse restaurante especializado em receitas de Frango!"
authors = ["Arthur Guilherme e João Batista <arthur.gsf07@gmail.com>"]
requires-python = ">=3.11"
dependencies = []
